# USBポート /dev/ttyACM* (デフォルト：/dev/ttyACM_hayate)
port: /dev/ttyACM_hayate

# USBシリアルボーレート (デフォルト：115200 bps)
baud: 115200

# 加速度センサ、ジャイロセンサ、6軸または9軸融合四元数の出力レート(デフォルト：200Hz、レンジ：Min 1Hz ～ Max 200Hz)
output_rate_a: 200

# 地磁気出力レート(デフォルト：70Hz、レンジ：Min 1Hz ～ Max 70Hz))
output_rate_m: 70
