# USBポート /dev/ttyACM* (デフォルト：/dev/ttyACM_hayate)
port: /dev/ttyACM_hayate
#port: /dev/ttyACM0

# USBシリアルボーレート (デフォルト：115200 bps)
baud: 115200

# 6軸センサフュージョン or 9軸センサフュージョン (デフォルト：9軸センサフュージョン)
fusion: 9

# 加速度センサ、ジャイロセンサ、6軸または9軸融合四元数の出力レート(デフォルト：200Hz、レンジ：Min 50Hz ～ Max 225Hz)
output_rate_q: 200

# 加速度センサ、ジャイロセンサ、6軸または9軸融合四元数の出力レート(デフォルト：1Hz、レンジ：Min 1Hz ～ Max 225Hz)
output_rate_a: 1

# 地磁気出力レート(デフォルト：1Hz、レンジ：Min 1Hz ～ Max 75Hz))
output_rate_m: 1

# 加速度センサバイアスX(デフォルト：0、納品書に記載)
bias_accel_x: 0

# 加速度センサバイアスY(デフォルト：0、納品書に記載)
bias_accel_y: 0

# 加速度センサバイアスZ(デフォルト：0、納品書に記載)
bias_accel_z: 0

# ジャイロセンサバイアスX(デフォルト：0、納品書に記載)
bias_gyro_x: 0

# ジャイロセンサバイアスY(デフォルト：0、納品書に記載)
bias_gyro_y: 0

# ジャイロセンサバイアスZ(デフォルト：0、納品書に記載)
bias_gyro_z: 0

# 地磁気センサバイアスX(デフォルト：0、納品書に記載)
bias_magnet_x: 0

# 地磁気センサバイアスY(デフォルト：0、納品書に記載)
bias_magnet_y: 0

# 地磁気センサバイアスZ(デフォルト：0、納品書に記載)
bias_magnet_z: 0

